spring:
  application:
   name: kloudblogs-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/kloudblogs
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update  

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: kloudblogs-service   
 
